services:
  mongo:
    image: mongo:7
    container_name: rollercoin-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rollercoin
      MONGO_INITDB_ROOT_PASSWORD: rollerpass
      MONGO_INITDB_DATABASE: rollerdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: